apiVersion: v1
kind: Service
metadata:
  name: hiap-service-test
  namespace: default
  labels:
    app: hiap-test
spec:
  selector:
    app: hiap-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
  type: ClusterIP