apiVersion: v1
kind: Service
metadata:
  name: hiap-service-prod
  namespace: default
  labels:
    app: hiap-prod
spec:
  selector:
    app: hiap-prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
  type: ClusterIP
