apiVersion: v1
kind: Service
metadata:
  name: hiap-service
  namespace: default
  labels:
    app: hiap
spec:
  selector:
    app: hiap
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
  type: ClusterIP