#!/usr/bin/env python3
# Generated by scripts/generate_schema.py — do not edit manually
"""Generate schema.dbml, schema.md (Mermaid erDiagram), and LAST_SYNCED.md
from Alembic migration files, without requiring a live database connection.

Run from the project root:
    python scripts/generate_schema.py
"""

import importlib.util
import re
import subprocess
import sys
import types
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import sqlalchemy as sa
from sqlalchemy import MetaData

# ── Paths ──────────────────────────────────────────────────────────────────────

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent                              # global-api/
MIGRATIONS_DIR = ROOT / "migrations" / "versions"
ALEMBIC_INI = ROOT / "alembic.ini"
OUT_DIR = ROOT / "data-model" / "physical-model"

DBML_FILE = OUT_DIR / "schema.dbml"
MD_FILE = OUT_DIR / "schema.md"
LAST_SYNCED_FILE = OUT_DIR / "LAST_SYNCED.md"

SCRIPT_REL = "python scripts/generate_schema.py"

# ── Type helpers ───────────────────────────────────────────────────────────────

def _normalize_sa_type(col_type: Any) -> Any:
    """Replace PostgreSQL-specific types with portable SQLAlchemy equivalents."""
    try:
        from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY as PG_ARRAY
        if isinstance(col_type, UUID):
            return col_type
        if isinstance(col_type, JSONB):
            return sa.JSON()
        if isinstance(col_type, PG_ARRAY):
            return sa.Text()
    except ImportError:
        pass
    # Handle dialect-qualified types accessed via sa.dialects.postgresql.*
    type_cls_name = type(col_type).__name__
    if type_cls_name in ("UUID",):
        return col_type
    if type_cls_name in ("JSONB",):
        return sa.JSON()
    if type_cls_name in ("ARRAY",):
        return sa.Text()
    return col_type


def _sa_type_to_mermaid(col_type: Any) -> str:
    mapping = {
        "Integer": "int",
        "BigInteger": "int",
        "SmallInteger": "int",
        "String": "string",
        "Text": "string",
        "VARCHAR": "string",
        "CHAR": "string",
        "Unicode": "string",
        "UnicodeText": "string",
        "Boolean": "boolean",
        "DateTime": "datetime",
        "Date": "datetime",
        "Time": "datetime",
        "Float": "float",
        "Numeric": "float",
        "JSON": "json",
        "JSONB": "json",
        "UUID": "string",
        "Uuid": "string",
        "ARRAY": "string",
        "LargeBinary": "string",
        "Enum": "string",
        "NullType": "string",
    }
    return mapping.get(type(col_type).__name__, "string")


def _sa_type_to_dbml(col_type: Any) -> str:
    mapping = {
        "Integer": "integer",
        "BigInteger": "bigint",
        "SmallInteger": "smallint",
        "String": "varchar",
        "Text": "text",
        "VARCHAR": "varchar",
        "CHAR": "char",
        "Boolean": "boolean",
        "DateTime": "datetime",
        "Date": "date",
        "Time": "time",
        "Float": "float",
        "Numeric": "decimal",
        "JSON": "json",
        "UUID": "uuid",
        "Uuid": "uuid",
        "LargeBinary": "blob",
        "NullType": "varchar",
    }
    return mapping.get(type(col_type).__name__, "varchar")


# ── Raw-SQL CREATE TABLE parser ────────────────────────────────────────────────

_SQL_RAW_TYPE_MAP: Dict[str, Any] = {
    "varchar": sa.String,
    "character varying": sa.String,
    "text": sa.Text,
    "int": sa.Integer,
    "integer": sa.Integer,
    "bigint": sa.BigInteger,
    "smallint": sa.SmallInteger,
    "serial": sa.Integer,
    "bigserial": sa.BigInteger,
    "float": sa.Float,
    "double precision": sa.Float,
    "real": sa.Float,
    "numeric": sa.Numeric,
    "decimal": sa.Numeric,
    "boolean": sa.Boolean,
    "bool": sa.Boolean,
    "date": sa.Date,
    "timestamp": sa.DateTime,
    "timestamptz": sa.DateTime,
    "timestamp with time zone": sa.DateTime,
    "timestamp without time zone": sa.DateTime,
    "json": sa.JSON,
    "jsonb": sa.JSON,
    "uuid": sa.UUID,
    "char": sa.String,
}


def _raw_sql_type(raw: str) -> Any:
    s = raw.strip().lower()
    s = re.sub(r"\[\]", "", s)                        # strip array suffix
    s = re.sub(r"\(\s*\d+(?:\s*,\s*\d+)?\s*\)", "", s)  # strip (n) / (n,m)
    s = s.strip()
    for key, typ in _SQL_RAW_TYPE_MAP.items():
        if s == key or s.startswith(key + " "):
            return typ()
    return sa.Text()


def _split_top_level(text: str, sep: str = ",") -> List[str]:
    """Split `text` by `sep` respecting parenthesis depth."""
    parts: List[str] = []
    current: List[str] = []
    depth = 0
    for ch in text:
        if ch == "(":
            depth += 1
            current.append(ch)
        elif ch == ")":
            depth -= 1
            current.append(ch)
        elif ch == sep and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current))
    return parts


def _parse_sql_rename_tables(sql: str, metadata: MetaData) -> None:
    """Handle ALTER TABLE old_name RENAME TO new_name statements in raw SQL."""
    pattern = re.compile(
        r"ALTER\s+TABLE\s+(?:(?P<schema1>\w+)\.)?\"?(?P<old>\w+)\"?\s+RENAME\s+TO\s+\"?(?P<new>\w+)\"?",
        re.IGNORECASE,
    )
    for m in pattern.finditer(sql):
        schema = m.group("schema1")
        old_name = m.group("old")
        new_name = m.group("new")
        old_key = f"{schema}.{old_name}" if schema else old_name
        if old_key not in metadata.tables:
            old_key = old_name  # try without schema
        if old_key not in metadata.tables:
            continue
        old_table = metadata.tables[old_key]
        cols = [
            sa.Column(c.name, c.type, primary_key=c.primary_key, nullable=c.nullable)
            for c in old_table.columns
        ]
        metadata.remove(old_table)
        try:
            sa.Table(new_name, metadata, *cols, schema=schema)
        except Exception:
            pass


def _parse_sql_drop_tables(sql: str, metadata: MetaData) -> None:
    """Handle DROP TABLE [IF EXISTS] [schema.]table statements in raw SQL."""
    pattern = re.compile(
        r"DROP\s+TABLE\s+(?:IF\s+EXISTS\s+)?(?:(?P<schema>\w+)\.)?\"?(?P<table>\w+)\"?",
        re.IGNORECASE,
    )
    for m in pattern.finditer(sql):
        schema = m.group("schema")
        table_name = m.group("table")
        key = f"{schema}.{table_name}" if schema else table_name
        if key in metadata.tables:
            metadata.remove(metadata.tables[key])
        elif table_name in metadata.tables:
            metadata.remove(metadata.tables[table_name])


def _parse_sql_create_tables(sql: str, metadata: MetaData) -> None:
    """Parse CREATE TABLE … statements from a SQL string and add to metadata."""
    # Strip line comments
    sql_stripped = re.sub(r"--[^\n]*", " ", sql)

    pattern = re.compile(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?"
        r'(?:"?(\w+)"?\.)?'
        r'"?(\w+)"?\s*\((.*?)\)\s*;',
        re.IGNORECASE | re.DOTALL,
    )

    for m in pattern.finditer(sql_stripped):
        schema = m.group(1) or None
        table_name = m.group(2)
        body = m.group(3)

        table_key = f"{schema}.{table_name}" if schema else table_name
        if table_key in metadata.tables:
            continue

        columns: List[sa.Column] = []
        pk_cols: List[str] = []

        for part in _split_top_level(body):
            part = part.strip()
            if not part:
                continue
            upper = part.upper().lstrip()

            # Table-level constraints
            if re.match(r"CONSTRAINT\b", upper, re.IGNORECASE):
                # Look for inline PK inside CONSTRAINT
                pk_m = re.search(r"PRIMARY\s+KEY\s*\(([^)]+)\)", part, re.IGNORECASE)
                if pk_m:
                    pk_cols += [c.strip().strip('"') for c in pk_m.group(1).split(",")]
                continue
            if re.match(r"(PRIMARY|FOREIGN|UNIQUE|CHECK)\b", upper, re.IGNORECASE):
                pk_m = re.search(r"PRIMARY\s+KEY\s*\(([^)]+)\)", part, re.IGNORECASE)
                if pk_m:
                    pk_cols += [c.strip().strip('"') for c in pk_m.group(1).split(",")]
                continue

            # Column definition: "name" TYPE [modifiers]
            col_m = re.match(r'"?(\w+)"?\s+(\S.*)', part, re.IGNORECASE)
            if not col_m:
                continue
            col_name = col_m.group(1)
            rest = col_m.group(2)

            # Extract type (everything up to NOT NULL / NULL / DEFAULT / PRIMARY KEY / REFERENCES)
            type_m = re.match(
                r"([\w\s]+?(?:\[\])?(?:\(\s*\d+(?:\s*,\s*\d+)?\s*\))?)\s*"
                r"(?:NOT\s+NULL|NULL|\bDEFAULT\b|\bPRIMARY\b|\bREFERENCES\b|$)",
                rest,
                re.IGNORECASE,
            )
            type_str = type_m.group(1).strip() if type_m else rest.split()[0]

            is_pk = bool(re.search(r"\bPRIMARY\s+KEY\b", part, re.IGNORECASE))
            is_nullable = not bool(re.search(r"\bNOT\s+NULL\b", part, re.IGNORECASE))

            columns.append(
                sa.Column(col_name, _raw_sql_type(type_str), nullable=is_nullable, primary_key=is_pk)
            )

        # Apply table-level PKs
        for col in columns:
            if col.name in pk_cols:
                col.primary_key = True

        if columns:
            try:
                sa.Table(table_name, metadata, *columns, schema=schema)
            except Exception:
                pass


# ── Mock Alembic infrastructure ────────────────────────────────────────────────

class _MockInspector:
    def __init__(self, metadata: MetaData):
        self._meta = metadata

    def get_schema_names(self) -> List[str]:
        schemas = {"public"}
        for t in self._meta.tables.values():
            if t.schema:
                schemas.add(t.schema)
        return list(schemas)

    def get_table_names(self, schema: Optional[str] = None) -> List[str]:
        results = []
        for t in self._meta.tables.values():
            if schema in (None, "public"):
                if t.schema is None:
                    results.append(t.name)
            elif t.schema == schema:
                results.append(t.name)
        return results

    def get_column_names(self, table_name: str, schema: Optional[str] = None) -> List[str]:
        key = f"{schema}.{table_name}" if schema else table_name
        t = self._meta.tables.get(key)
        return [c.name for c in t.columns] if t else []


class _MockResult:
    def fetchall(self):
        return []

    def fetchone(self):
        return None

    def __iter__(self):
        return iter([])

    def scalar(self):
        return None


class _MockConnection:
    """Captures CREATE TABLE SQL from conn.execute(text(...))."""

    def __init__(self, metadata: MetaData):
        self._meta = metadata

    def execute(self, stmt: Any, *args: Any, **kwargs: Any) -> _MockResult:
        sql = str(stmt)
        _parse_sql_create_tables(sql, self._meta)
        _parse_sql_rename_tables(sql, self._meta)
        _parse_sql_drop_tables(sql, self._meta)
        return _MockResult()

    def close(self) -> None:
        pass


class _MockBatchOp:
    def add_column(self, *a: Any, **kw: Any) -> None: pass
    def drop_column(self, *a: Any, **kw: Any) -> None: pass
    def alter_column(self, *a: Any, **kw: Any) -> None: pass
    def create_foreign_key(self, *a: Any, **kw: Any) -> None: pass
    def drop_constraint(self, *a: Any, **kw: Any) -> None: pass
    def create_index(self, *a: Any, **kw: Any) -> None: pass
    def drop_index(self, *a: Any, **kw: Any) -> None: pass
    def __enter__(self): return self
    def __exit__(self, *a: Any) -> None: pass


class _MockOp:
    def __init__(self, metadata: MetaData):
        self._meta = metadata
        self._conn = _MockConnection(metadata)

    # ── table-level ops ────────────────────────────────────────────────────────

    def create_table(
        self,
        table_name: str,
        *args: Any,
        schema: Optional[str] = None,
        **kwargs: Any,
    ) -> None:
        table_key = f"{schema}.{table_name}" if schema else table_name
        if table_key in self._meta.tables:
            return

        cols: List[sa.Column] = []
        constraints: List[Any] = []
        for a in args:
            if isinstance(a, sa.Column):
                try:
                    col_type = _normalize_sa_type(a.type)
                    new_col = sa.Column(
                        a.name,
                        col_type,
                        primary_key=a.primary_key,
                        nullable=a.nullable,
                    )
                    # Carry over ForeignKey objects from the original column
                    for fk in list(a.foreign_keys):
                        try:
                            new_col.foreign_keys.add(sa.ForeignKey(fk.target_fullname))
                        except Exception:
                            pass
                    cols.append(new_col)
                except Exception:
                    cols.append(a)
            elif isinstance(a, (sa.PrimaryKeyConstraint, sa.UniqueConstraint, sa.CheckConstraint)):
                constraints.append(a)
            elif isinstance(a, sa.ForeignKeyConstraint):
                # Include FK constraints for relationship tracking
                constraints.append(a)

        try:
            sa.Table(table_name, self._meta, *cols, *constraints, schema=schema)
        except Exception:
            # If constraints cause issues, try without them
            try:
                sa.Table(table_name, self._meta, *cols, schema=schema)
            except Exception:
                pass

    def drop_table(
        self, table_name: str, schema: Optional[str] = None, **kwargs: Any
    ) -> None:
        key = f"{schema}.{table_name}" if schema else table_name
        if key in self._meta.tables:
            self._meta.remove(self._meta.tables[key])

    def rename_table(
        self, old_name: str, new_name: str, schema: Optional[str] = None, **kwargs: Any
    ) -> None:
        old_key = f"{schema}.{old_name}" if schema else old_name
        if old_key not in self._meta.tables:
            return
        old_table = self._meta.tables[old_key]
        cols = [
            sa.Column(c.name, c.type, primary_key=c.primary_key, nullable=c.nullable)
            for c in old_table.columns
        ]
        self._meta.remove(old_table)
        try:
            sa.Table(new_name, self._meta, *cols, schema=schema)
        except Exception:
            pass

    # ── column-level ops ───────────────────────────────────────────────────────

    def add_column(
        self,
        table_name: str,
        column: sa.Column,
        schema: Optional[str] = None,
        **kwargs: Any,
    ) -> None:
        key = f"{schema}.{table_name}" if schema else table_name
        table = self._meta.tables.get(key)
        if table is None:
            return
        if column.name in table.c:
            return
        try:
            col_type = _normalize_sa_type(column.type)
            new_col = sa.Column(
                column.name, col_type, primary_key=column.primary_key, nullable=column.nullable
            )
            table.append_column(new_col)
        except Exception:
            pass

    def drop_column(
        self,
        table_name: str,
        column_name: str,
        schema: Optional[str] = None,
        **kwargs: Any,
    ) -> None:
        # Intentionally left as a no-op: dropped columns stay in documentation.
        pass

    def alter_column(self, *args: Any, **kwargs: Any) -> None:
        pass

    # ── constraint / index ops ────────────────────────────────────────────────

    def create_foreign_key(
        self,
        constraint_name: Any,
        source_table: str,
        referent_table: str,
        local_cols: List[str],
        remote_cols: List[str],
        source_schema: Optional[str] = None,
        referent_schema: Optional[str] = None,
        **kwargs: Any,
    ) -> None:
        pass

    def drop_constraint(self, *args: Any, **kwargs: Any) -> None:
        pass

    def create_primary_key(self, *args: Any, **kwargs: Any) -> None:
        pass

    def create_index(self, *args: Any, **kwargs: Any) -> None:
        pass

    def drop_index(self, *args: Any, **kwargs: Any) -> None:
        pass

    def create_check_constraint(self, *args: Any, **kwargs: Any) -> None:
        pass

    def create_unique_constraint(self, *args: Any, **kwargs: Any) -> None:
        pass

    @staticmethod
    def f(name: str) -> str:
        """Alembic naming convention helper — just returns the name."""
        return name

    # ── schema ops ────────────────────────────────────────────────────────────

    def execute(self, stmt: Any, *args: Any, **kwargs: Any) -> _MockResult:
        sql = str(stmt)
        _parse_sql_create_tables(sql, self._meta)
        _parse_sql_rename_tables(sql, self._meta)
        _parse_sql_drop_tables(sql, self._meta)
        return _MockResult()

    def get_bind(self) -> _MockConnection:
        return self._conn

    def batch_alter_table(self, *args: Any, **kwargs: Any) -> _MockBatchOp:
        return _MockBatchOp()


# ── Migration loading & ordering ───────────────────────────────────────────────

def _load_migration_modules(migrations_dir: Path) -> Dict[str, Any]:
    """Import each migration file and return {revision: module}."""
    modules: Dict[str, Any] = {}
    for path in sorted(migrations_dir.glob("*.py")):
        if path.name.startswith("__"):
            continue
        spec = importlib.util.spec_from_file_location(f"_migration_{path.stem}", path)
        mod = importlib.util.module_from_spec(spec)
        try:
            spec.loader.exec_module(mod)  # type: ignore[union-attr]
        except Exception as exc:
            print(f"  [skip] {path.name}: {exc}")
            continue
        rev = getattr(mod, "revision", None)
        if rev:
            modules[rev] = mod
    return modules


def _topological_order(modules: Dict[str, Any]) -> List[Any]:
    """Return modules sorted so each migration runs after its dependency."""
    visited: set = set()
    order: List[Any] = []

    def visit(rev: str) -> None:
        if rev in visited:
            return
        visited.add(rev)
        mod = modules.get(rev)
        if mod is None:
            return
        down = mod.down_revision
        if isinstance(down, (list, tuple)):
            for d in down:
                visit(d)
        elif down:
            visit(down)
        order.append(mod)

    for rev in modules:
        visit(rev)

    return order


# ── MetaData construction ──────────────────────────────────────────────────────

def build_metadata() -> MetaData:
    """Replay all migration upgrades with a mock op to reconstruct MetaData."""
    metadata = MetaData()
    mock_op = _MockOp(metadata)

    # Build a module-like object to serve as alembic.op
    mock_op_module = types.ModuleType("alembic.op")
    for name in dir(mock_op):
        if not name.startswith("__"):
            setattr(mock_op_module, name, getattr(mock_op, name))

    import alembic

    orig_op_module = sys.modules.get("alembic.op")
    orig_alembic_op_attr = getattr(alembic, "op", None)
    orig_sa_inspect = sa.inspect

    sys.modules["alembic.op"] = mock_op_module
    alembic.op = mock_op_module  # type: ignore[attr-defined]

    def _mock_inspect(bind: Any) -> _MockInspector:
        return _MockInspector(metadata)

    sa.inspect = _mock_inspect  # type: ignore[assignment]

    try:
        modules = _load_migration_modules(MIGRATIONS_DIR)
        ordered = _topological_order(modules)
        print(f"  Loaded {len(modules)} migration files, replaying in order…")

        for mod in ordered:
            try:
                mod.upgrade()
            except Exception as exc:
                print(f"  [warn] migration {mod.revision} upgrade() raised: {exc}")
    finally:
        if orig_op_module is not None:
            sys.modules["alembic.op"] = orig_op_module
        else:
            sys.modules.pop("alembic.op", None)
        if orig_alembic_op_attr is not None:
            alembic.op = orig_alembic_op_attr  # type: ignore[attr-defined]
        sa.inspect = orig_sa_inspect  # type: ignore[assignment]

    return metadata


# ── Alembic head revision ──────────────────────────────────────────────────────

def get_alembic_head() -> str:
    """Return the current alembic head revision string, or 'unknown'."""
    try:
        result = subprocess.run(
            ["alembic", "-c", str(ALEMBIC_INI), "heads"],
            capture_output=True,
            text=True,
            timeout=15,
            cwd=str(ROOT),
        )
        if result.returncode == 0:
            # "abc123 (head)" or "abc123\nabc456 (head)" for multiple heads
            heads = re.findall(r"([0-9a-f]{12,})", result.stdout)
            if heads:
                return ", ".join(heads)
        return "unknown"
    except Exception:
        return "unknown"


# ── DBML generation ────────────────────────────────────────────────────────────

def _dbml_fallback(metadata: MetaData) -> str:
    """Generate DBML from MetaData without the sqlalchemy-dbml library."""
    lines: List[str] = [
        "// Generated by scripts/generate_schema.py — do not edit manually",
        "",
    ]

    # TableGroups per schema
    by_schema: Dict[str, List[Any]] = defaultdict(list)
    for table in sorted(metadata.tables.values(), key=lambda t: (t.schema or "", t.name)):
        by_schema[table.schema or "public"].append(table)

    for schema_name, tables in sorted(by_schema.items()):
        if schema_name != "public":
            lines.append(f"TableGroup {schema_name} {{")
            for t in tables:
                lines.append(f'  "{schema_name}"."{t.name}"')
            lines.append("}")
            lines.append("")

    # Table definitions
    for table in sorted(metadata.tables.values(), key=lambda t: (t.schema or "", t.name)):
        qual_name = f'"{table.schema}"."{table.name}"' if table.schema else f'"{table.name}"'
        lines.append(f"Table {qual_name} {{")
        for col in table.columns:
            dbml_type = _sa_type_to_dbml(col.type)
            attrs: List[str] = []
            if col.primary_key:
                attrs.append("pk")
            if not col.nullable and not col.primary_key:
                attrs.append("not null")
            attr_str = f" [{', '.join(attrs)}]" if attrs else ""
            lines.append(f'  "{col.name}" {dbml_type}{attr_str}')
        lines.append("}")
        lines.append("")

    # References
    refs_seen: set = set()
    for table in sorted(metadata.tables.values(), key=lambda t: (t.schema or "", t.name)):
        src_name = f'"{table.schema}"."{table.name}"' if table.schema else f'"{table.name}"'
        for constraint in table.constraints:
            if not isinstance(constraint, sa.ForeignKeyConstraint):
                continue
            for fk in constraint.elements:
                try:
                    tgt_col = fk.column
                    tgt_table = tgt_col.table
                    tgt_name = (
                        f'"{tgt_table.schema}"."{tgt_table.name}"'
                        if tgt_table.schema
                        else f'"{tgt_table.name}"'
                    )
                    src_col_name = fk.parent.name
                    ref_key = f"{src_name}.{src_col_name}->{tgt_name}.{tgt_col.name}"
                    if ref_key not in refs_seen:
                        refs_seen.add(ref_key)
                        lines.append(
                            f'Ref: {src_name}."{src_col_name}" > {tgt_name}."{tgt_col.name}"'
                        )
                except Exception:
                    pass
        # Also check per-column FKs
        for col in table.columns:
            for fk in col.foreign_keys:
                try:
                    tgt_col = fk.column
                    tgt_table = tgt_col.table
                    tgt_name = (
                        f'"{tgt_table.schema}"."{tgt_table.name}"'
                        if tgt_table.schema
                        else f'"{tgt_table.name}"'
                    )
                    ref_key = f"{src_name}.{col.name}->{tgt_name}.{tgt_col.name}"
                    if ref_key not in refs_seen:
                        refs_seen.add(ref_key)
                        lines.append(
                            f'Ref: {src_name}."{col.name}" > {tgt_name}."{tgt_col.name}"'
                        )
                except Exception:
                    pass

    return "\n".join(lines)


def generate_dbml(metadata: MetaData) -> str:
    """Generate DBML string, using sqlalchemy-dbml if available."""
    try:
        # sqlalchemy-dbml exposes generate() or dump() depending on version
        from sqlalchemy_dbml import generate as dbml_generate  # type: ignore

        raw = dbml_generate(metadata)
        header = "// Generated by scripts/generate_schema.py — do not edit manually\n\n"
        return header + raw
    except ImportError:
        pass
    except Exception as exc:
        print(f"  [warn] sqlalchemy-dbml raised {exc}; using built-in DBML generator")

    return _dbml_fallback(metadata)


# ── Mermaid erDiagram generation ───────────────────────────────────────────────

def _entity_name(schema: Optional[str], table_name: str) -> str:
    """Return a Mermaid-safe entity identifier."""
    if schema:
        return f"{schema}__{table_name}"
    return table_name


def generate_mermaid(metadata: MetaData) -> str:
    """Return a Mermaid erDiagram block from SQLAlchemy MetaData."""
    lines = ["erDiagram"]
    relationships: List[str] = []
    rel_seen: set = set()

    for table in sorted(metadata.tables.values(), key=lambda t: (t.schema or "", t.name)):
        entity = _entity_name(table.schema, table.name)
        lines.append(f"    {entity} {{")

        for col in table.columns:
            col_type = _sa_type_to_mermaid(col.type)
            annotations: List[str] = []
            if col.primary_key:
                annotations.append("PK")
            if col.foreign_keys:
                annotations.append("FK")
            ann_str = f' "{", ".join(annotations)}"' if annotations else ""
            lines.append(f"        {col_type} {col.name}{ann_str}")

        lines.append("    }")

        # Collect FK relationships
        fk_pairs: set = set()
        for col in table.columns:
            for fk in col.foreign_keys:
                try:
                    tgt_table = fk.column.table
                    tgt_entity = _entity_name(tgt_table.schema, tgt_table.name)
                    pair = (entity, tgt_entity)
                    fk_pairs.add(pair)
                except Exception:
                    pass
        for constraint in table.constraints:
            if isinstance(constraint, sa.ForeignKeyConstraint):
                for fk in constraint.elements:
                    try:
                        tgt_table = fk.column.table
                        tgt_entity = _entity_name(tgt_table.schema, tgt_table.name)
                        pair = (entity, tgt_entity)
                        fk_pairs.add(pair)
                    except Exception:
                        pass

        for src, tgt in fk_pairs:
            key = f"{src}--{tgt}"
            if key not in rel_seen:
                rel_seen.add(key)
                relationships.append(f"    {src} }}o--|| {tgt} : references")

    if relationships:
        lines.append("")
        lines.extend(sorted(relationships))

    return "\n".join(lines)


# ── File writers ───────────────────────────────────────────────────────────────

def write_dbml(metadata: MetaData, ts: str, revision: str) -> None:
    dbml = generate_dbml(metadata)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DBML_FILE.write_text(dbml, encoding="utf-8")


def write_schema_md(metadata: MetaData, ts: str, revision: str) -> None:
    mermaid = generate_mermaid(metadata)
    content = f"""<!-- Generated by scripts/generate_schema.py — do not edit manually -->
# Database Schema

**Last generated:** {ts}
**Alembic revision:** `{revision}`

```mermaid
{mermaid}
```
"""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    MD_FILE.write_text(content, encoding="utf-8")


def write_last_synced(ts: str, revision: str) -> None:
    content = f"""# LAST_SYNCED

| Field | Value |
|---|---|
| Generated at | {ts} |
| Alembic revision | `{revision}` |
| Regenerate | `{SCRIPT_REL}` |
"""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    LAST_SYNCED_FILE.write_text(content, encoding="utf-8")


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    # Ensure imports resolve relative to the project root when run as a script
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))

    print("generate_schema.py")
    print("=" * 60)

    print("\n[1/4] Fetching Alembic head revision…")
    revision = get_alembic_head()
    print(f"      revision: {revision}")

    print("\n[2/4] Replaying migrations to reconstruct MetaData…")
    metadata = build_metadata()
    table_count = len(metadata.tables)
    print(f"      tables found: {table_count}")

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    print("\n[3/4] Generating output files…")

    write_dbml(metadata, ts, revision)
    print(f"      wrote {DBML_FILE.relative_to(ROOT)}")

    write_schema_md(metadata, ts, revision)
    print(f"      wrote {MD_FILE.relative_to(ROOT)}")

    write_last_synced(ts, revision)
    print(f"      wrote {LAST_SYNCED_FILE.relative_to(ROOT)}")

    print("\n[4/4] Summary")
    print(f"      Tables discovered : {table_count}")
    print(f"      Alembic revision  : {revision}")
    print(f"      Files written     : {DBML_FILE.name}, {MD_FILE.name}, {LAST_SYNCED_FILE.name}")
    print(f"      Output directory  : {OUT_DIR.relative_to(ROOT)}")
    print("\nDone.")


if __name__ == "__main__":
    main()
