apiVersion: batch/v1
kind: CronJob
metadata:
  name: cc-prod-sync-catalogue
spec:
  # run every monday
  schedule: 0 0 * * 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cc-sync-catalogue
            image: ghcr.io/open-earth-foundation/citycatalyst:stable
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: cc-db-configmap
            env:
            - name: NODE_ENV
              value: development
            - name: GLOBAL_API_URL
              value: "https://api.citycatalyst.io/"
            command: ["/bin/sh", "-c"]
            args: ["npx tsx scripts/catalogue-sync.ts && npx tsx scripts/formula-values-sync.ts && npx tsx scripts/emissions-factors-sync.ts"]
            resources:
              limits:
                memory: "1024Mi"
                cpu: "1000m"
