apiVersion: batch/v1
kind: Job
metadata:
  generateName: cc-prod-seed-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cc-seed
        image: ghcr.io/open-earth-foundation/citycatalyst:stable
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: cc-db-configmap
        env:
        - name: NODE_ENV
          value: development
        command: ["npm",  "run", "db:seed"]
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
