/**
 * Inventory of tables that hold personal data.
 *
 * DSAR export iterates this list. A table is covered only when it appears
 * here and a collector in DsarExportService uses the same `table` name.
 * Greenhouse-gas inventory contents are organizational data about a city and
 * are not included; uploader identity and file names are.
 */
export interface PersonalDataDataset {
  /** Sequelize model name. Must match a DSAR collector key. */
  table: string;
  purpose: string;
  legalBasis: string;
  /** Columns joined into the CSV record_id. */
  idFields: string[];
  /** Exported as stored. */
  fields: string[];
  /** Replaced with "[redacted]" when a value is stored. The secret is never exported. */
  redactedFields?: string[];
  /** Present in the table and deliberately left out of the export. */
  omittedFields?: string[];
}

export const PERSONAL_DATA_INVENTORY: PersonalDataDataset[] = [
  {
    table: "User",
    purpose: "Account profile for a signed-in person.",
    legalBasis: "Contract (Art. 6(1)(b)) and access obligation (Art. 15).",
    idFields: ["userId"],
    fields: [
      "userId",
      "name",
      "email",
      "title",
      "pictureUrl",
      "preferredLanguage",
      "numberFormat",
      "role",
      "defaultCityId",
      "defaultInventoryId",
      "twoFactorEnabled",
      "lastActiveAt",
      "anonymizedAt",
      "created",
      "lastUpdated",
    ],
    redactedFields: [
      "passwordHash",
      "twoFactorSecret",
      "twoFactorRecoveryHashes",
    ],
  },
  {
    table: "CityUser",
    purpose: "Cities the person is a member of.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["cityUserId"],
    fields: ["cityUserId", "userId", "cityId", "created", "lastUpdated"],
  },
  {
    table: "CityInvite",
    purpose: "City invitations sent to or by the person.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["id"],
    fields: [
      "id",
      "cityId",
      "userId",
      "invitingUserId",
      "email",
      "status",
      "created",
      "lastUpdated",
    ],
  },
  {
    table: "OrganizationInvite",
    purpose: "Organization invitations sent to the person.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["id"],
    fields: [
      "id",
      "organizationId",
      "userId",
      "email",
      "role",
      "status",
      "created",
      "lastUpdated",
    ],
  },
  {
    table: "ProjectInvite",
    purpose: "Project invitations sent to the person.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["id"],
    fields: [
      "id",
      "projectId",
      "userId",
      "email",
      "status",
      "created",
      "lastUpdated",
    ],
  },
  {
    table: "OrganizationAdmin",
    purpose: "Organization administrator membership.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["organizationAdminId"],
    fields: [
      "organizationAdminId",
      "organizationId",
      "userId",
      "created",
      "lastUpdated",
    ],
  },
  {
    table: "ProjectAdmin",
    purpose: "Project administrator membership.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["projectAdminId"],
    fields: ["projectAdminId", "projectId", "userId", "created", "lastUpdated"],
  },
  {
    table: "Organization",
    purpose:
      "Organization contact email when it is the same address as the person's account.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["organizationId"],
    fields: ["organizationId", "name", "contactEmail"],
  },
  {
    table: "UserFile",
    purpose: "Metadata for files the person uploaded.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["id"],
    fields: [
      "id",
      "userId",
      "cityId",
      "fileName",
      "fileType",
      "fileReference",
      "url",
      "status",
      "sector",
      "gpcRefNo",
      "created",
      "lastUpdated",
    ],
    omittedFields: ["data"],
  },
  {
    table: "ImportedInventoryFile",
    purpose: "Metadata for inventory files the person imported.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["id"],
    fields: [
      "id",
      "userId",
      "cityId",
      "inventoryId",
      "fileName",
      "originalFileName",
      "fileType",
      "fileSize",
      "importStatus",
      "rowCount",
      "processedRowCount",
      "created",
      "lastUpdated",
      "completedAt",
    ],
    omittedFields: ["data", "s3Key", "contentDigest"],
  },
  {
    table: "PersonalAccessToken",
    purpose: "API tokens the person created.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["id"],
    fields: [
      "id",
      "userId",
      "name",
      "tokenPrefix",
      "scopes",
      "expiresAt",
      "lastUsedAt",
      "created",
      "lastUpdated",
    ],
    omittedFields: ["tokenHash"],
  },
  {
    table: "OAuthClientAuthz",
    purpose: "OAuth clients the person authorized.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["clientId", "userId"],
    fields: ["clientId", "userId", "lastUsed", "created"],
  },
  {
    table: "WebhookSubscription",
    purpose: "Webhook endpoints the person created.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["id"],
    fields: [
      "id",
      "organizationId",
      "name",
      "url",
      "events",
      "enabled",
      "createdBy",
      "created",
      "lastUpdated",
    ],
    omittedFields: ["secretCiphertext", "secretIv", "secretAuthTag", "secretPrefix"],
  },
  {
    table: "HighImpactActionRanking",
    purpose: "Prioritization jobs the person started.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["id"],
    fields: [
      "id",
      "userId",
      "inventoryId",
      "locode",
      "type",
      "status",
      "isBulk",
      "jobId",
      "created",
      "lastUpdated",
    ],
  },
  {
    table: "BulkInventoryImportJob",
    purpose: "Bulk import jobs the person started.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["id"],
    fields: [
      "id",
      "userId",
      "projectId",
      "year",
      "status",
      "totalCount",
      "importedCount",
      "failedCount",
      "skippedCount",
      "created",
      "lastUpdated",
    ],
    omittedFields: ["s3Key"],
  },
  {
    table: "MeedRanking",
    purpose: "MEED rankings the person requested.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["id"],
    fields: [
      "id",
      "userId",
      "inventoryId",
      "status",
      "actionCount",
      "created",
      "lastUpdated",
    ],
  },
  {
    table: "NativeInputCatalog",
    purpose: "Catalog rows attributed to the person.",
    legalBasis: "Contract (Art. 6(1)(b)).",
    idFields: ["id"],
    fields: [
      "id",
      "userId",
      "kind",
      "owningModule",
      "sourceType",
      "sourceId",
      "inventoryId",
      "cityId",
      "projectId",
      "organizationId",
      "availability",
      "created",
      "lastUpdated",
    ],
  },
  {
    table: "ConsentRecord",
    purpose: "Cookie and marketing consent grants and withdrawals.",
    legalBasis: "Legal obligation to demonstrate consent (Art. 7(1)).",
    idFields: ["consentRecordId"],
    fields: [
      "consentRecordId",
      "userId",
      "subjectKey",
      "consentType",
      "status",
      "policyVersion",
      "source",
      "userAgent",
      "ipAddress",
      "created",
    ],
  },
  {
    table: "RetentionActionLog",
    purpose: "Retention actions already taken for this person.",
    legalBasis: "Legal obligation to demonstrate storage limitation (Art. 5(1)(e)).",
    idFields: ["retentionActionLogId"],
    fields: [
      "retentionActionLogId",
      "policyKey",
      "action",
      "subjectType",
      "subjectId",
      "dryRun",
      "details",
      "created",
    ],
  },
];
