# Climate Advisor deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: climate-advisor-deploy
  labels:
    app: climate-advisor-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: climate-advisor-deploy
  template:
    metadata:
      labels:
        app: climate-advisor-deploy
    spec:
      containers:
        - name: climate-advisor-deploy
          image: ghcr.io/open-earth-foundation/citycatalyst-climate-advisor:latest
          # Set to Never for local
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: cc-climate-advisor-db-configmap
          env:
            - name: PROJECT_NAME
              value: "CityCatalyst Climate Advisor"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
              httpHeaders:
              - name: X-Liveness-Probe
                value: "True"
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: 8000
              httpHeaders:
              - name: X-Liveness-Probe
                value: "True"
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
