apiVersion: batch/v1
kind: Job
metadata:
  generateName: cc-create-admin-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cc-create-admin
          image: ghcr.io/open-earth-foundation/citycatalyst:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cc-db-configmap
          env:
            - name: NODE_ENV
              value: development
          command: ["npm", "run", "create-admin"]
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
