apiVersion: batch/v1
kind: CronJob
metadata:
  name: cc-db-backup
spec:
  # run every day at 4AM
  schedule: 0 4 * * *
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: cc-db-backup-pvc
          containers:
          - name: cc-db-backup
            image: postgres:15
            imagePullPolicy: Always
            env:
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_USER
                  name: cc-db-configmap
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_HOST
                  name: cc-db-configmap
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_NAME
                  name: cc-db-configmap
            - name: PGPASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_PASSWORD
                  name: cc-db-configmap
            args:
            - |
              pg_dump | gzip > /var/backups/citycatalyst-$(date +%Y%m%d).sql.gz
            command: ['/bin/bash', '-c']
            resources:
              limits:
                memory: "1024Mi"
                cpu: "1000m"
            volumeMounts:
            - mountPath: "/var/backups/"
              name: backup
