apiVersion: batch/v1
kind: CronJob
metadata:
  name: cc-db-backup
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: cc-db-backup-pvc
          containers:
          - name: cc-db-backup
            image: postgres:15
            imagePullPolicy: Always
            env:
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: cc-db-configmap
                  key: DATABASE_USER
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: cc-db-configmap
                  key: DATABASE_HOST
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: cc-db-configmap
                  key: DATABASE_NAME
            - name: PGPASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cc-db-configmap
                  key: DATABASE_PASSWORD
            command: ["/bin/bash", "-c"]
            args:
            - |
              pg_dump | gzip > /var/backups/citycatalyst-$(date +%Y%m%d).sql.gz
            resources:
              limits:
                memory: "1024Mi"
                cpu: "1000m"
            volumeMounts:
            - name: backup
              mountPath: /var/backups/
