apiVersion: batch/v1
kind: Job
metadata:
  generateName: cc-global-api-import-edgar-gridcell-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cc-global-api-import-edgar-gridcell
        image: ghcr.io/open-earth-foundation/citycatalyst-global-api:latest
        command: ["python", "importer/edgar/gridcelledgar_importer.py", "--database_uri", "postgresql://ccglobal:ccglobal@cc-global-api-db/ccglobal"]
        resources:
            limits:
              memory: "4096Mi"
              cpu: "1000m"