apiVersion: batch/v1
kind: Job
metadata:
  generateName: cc-global-api-import-osm-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cc-global-api
        image: ghcr.io/open-earth-foundation/citycatalyst-global-api:latest
        command: ["python", "importer/osm_importer.py", "--database_uri", "postgresql://ccglobal:ccglobal@cc-global-api-db/ccglobal", "--url", "https://drive.google.com/file/d/1_1nrKPnjr01Epwp1VqxWITMTw-dEYJAJ/view?usp=sharing", "--log_file", "/dev/stdout"]
