apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-global-api-deploy
  labels:
    app: cc-global-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-global-api
  template:
    metadata:
      labels:
        app: cc-global-api
    spec:
      containers:
        - name: cc-global-api
          image: ghcr.io/open-earth-foundation/global-api:latest
          # Set to Never for local
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: DATABASE_HOST
              value: "cc-db"
            - name: DATABASE_USER
              value: "citycatalyst"
            - name: DATABASE_PASSWORD
              value: "development"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
