apiVersion: batch/v1
kind: Job
metadata:
  generateName: cc-global-api-migrate-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cc-global-api
        image: ghcr.io/open-earth-foundation/citycatalyst-global-api:latest
        env:
        - name: ALEMBIC_URL
          valueFrom:
            configMapKeyRef:
              name: cc-global-api-db-configmap
              key: DB_URL
        command: ["alembic", "upgrade", "heads"]
