apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-global-api-db-deploy
  labels:
    app: global-api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: global-api-db
  template:
    metadata:
      labels:
        app: global-api-db
    spec:
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: cc-global-api-db-pvc
      containers:
        - name: postgresql
          image: postgres:15
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: "POSTGRES_USER"
              value: "ccglobal"
            - name: "POSTGRES_PASSWORD"
              value: "ccglobal"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/"
              name: postgres
