apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-global-api-deploy
  labels:
    app: cc-global-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-global-api
  template:
    metadata:
      labels:
        app: cc-global-api
    spec:
      containers:
        - name: cc-global-api
          image: ghcr.io/open-earth-foundation/citycatalyst-global-api:latest
          # Set to Never for local
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: cc-global-api-db-configmap
          env:
            - name: PROJECT_NAME
              value: "CityCatalyst Global API"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
              httpHeaders:
              - name: X-Liveness-Probe
                value: "True"
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: 8000
              httpHeaders:
              - name: X-Liveness-Probe
                value: "True"
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
