apiVersion: batch/v1
kind: Job
metadata:
  generateName: cc-global-api-import-edgar-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cc-global-api
        image: ghcr.io/open-earth-foundation/citycatalyst-global-api:latest
        command: ["importer/edgar/import_edgar.sh", "postgresql://ccglobal:ccglobal@cc-global-api-db/ccglobal"]
