apiVersion: batch/v1
kind: CronJob
metadata:
  name: cc-global-api-db-backup
spec:
  # run every day at 3AM
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: cc-global-api-db-backup-pvc
          containers:
          - name: cc-global-api-db-backup
            image: postgres:15
            imagePullPolicy: Always
            env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: cc-global-api-db-configmap
                  key: DB_HOST
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: cc-global-api-db-configmap
                  key: DB_PORT
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: cc-global-api-db-configmap
                  key: DB_USER
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: cc-global-api-db-configmap
                  key: DB_NAME
            - name: PGPASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cc-global-api-db-configmap
                  key: DB_PASSWORD
            command: ["/bin/bash", "-c"]
            args:
            - |
              pg_dump | gzip > /var/backups/ccglobal-$(date +%Y%m%d).sql.gz
            resources:
              limits:
                memory: "1024Mi"
                cpu: "1000m"
            volumeMounts:
            - name: backup
              mountPath: /var/backups/
