apiVersion: batch/v1
kind: Job
metadata:
  generateName: cc-global-api-migrate-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cc-global-api
        image: ghcr.io/open-earth-foundation/citycatalyst-global-api:latest
        env:
        - name: ALEMBIC_URL
          value: "postgresql://ccglobal:ccglobal@cc-global-api-db/ccglobal"
        command: ["alembic", "upgrade", "heads"]
