apiVersion: batch/v1
kind: Job
metadata:
  generateName: cc-sync-catalogue-manual-
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cc-sync-catalogue
          image: ghcr.io/open-earth-foundation/citycatalyst:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cc-db-configmap
          env:
            - name: NODE_ENV
              value: development
            - name: GLOBAL_API_URL
              value: "https://ccglobal.openearth.dev"
            - name: npm_config_yes
              value: "true"
          command: ["/bin/sh", "-c"]
          args: ["npx tsx scripts/catalogue-sync.ts && npx tsx scripts/formula-values-sync.ts"]
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
