apiVersion: batch/v1
kind: CronJob
metadata:
  name: cc-sync-catalogue
spec:
  # run every monday
  schedule: 0 0 * * 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cc-sync-catalogue
              image: ghcr.io/open-earth-foundation/citycatalyst:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: cc-db-configmap
              env:
                - name: NODE_ENV
                  value: "development"
                - name: npm_config_yes
                  value: "true"
              command: ["npx", "tsx", "scripts/catalogue-sync.ts"]
              resources:
                limits:
                  memory: "1024Mi"
                  cpu: "1000m"
