apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-web-deploy
  labels:
    app: cc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-web
  template:
    metadata:
      labels:
        app: cc-web
    spec:
      containers:
        - name: cc-web
          image: ghcr.io/open-earth-foundation/citycatalyst:latest
          # Set to Never for local
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: cc-db-configmap
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: NEXTAUTH_URL
              value: "https://citycatalyst.openearth.dev"
            - name: HOST
              value: "https://citycatalyst.openearth.dev"
            - name: SMTP_FROM_EMAIL
              value: "citycatalyst@openearth.dev"
            - name: SMTP_HOST
              value: "email-smtp.us-east-1.amazonaws.com"
            - name: SMTP_PORT
              value: "587"
            - name: GLOBAL_API_URL
              value: "https://ccglobal.openearth.dev"
            - name: NEXT_PUBLIC_OPENCLIMATE_API_URL
              value: "https://openclimate.openearth.dev"
            - name: CDP_MODE
              value: test
            - name: CHAT_PROVIDER
              value: "openai"
            - name: OPEN_AI_MODEL
              value: "gpt-4o-mini"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
