apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  restartPolicy: Never
  containers:
  - name: shell
    # any image with tar and sh; you can swap for ubuntu, busybox, etc.
    image: busybox:latest
    command: ["/bin/sh", "-c", "sleep 1d"]
    volumeMounts:
    - name: backup
      mountPath: /mnt/backup
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
  volumes:
  - name: backup
    persistentVolumeClaim:
      claimName: cc-db-backup-pvc
