CREATE OR REPLACE TABLE waste_ef AS 
WITH waste_ef_split AS (
SELECT 	ef_id,
		UNNEST(STRING_SPLIT(ipcc_sector_multi, '|')) AS ipcc_sector,
		gas_multi,
		fuel_1996,
		fuel_2006,
		c_pool,
		type_parameter,
		Description,
		technologies_paractises,
		parameters_conditions,
		region,
		control_paractises,
		properties,
		emissionsfactor_value,
		emissionsfactor_units,
		ipcc_equation,
		data_source,
		ipcc_worksheet,
		technical_reference,
		dataset_name
FROM waste_ef),
waste_ef_split_gas AS (
SELECT 	ef_id,
		ipcc_sector,
		UNNEST(STRING_SPLIT(gas_multi, '|')) AS gas,
		fuel_1996,
		fuel_2006,
		c_pool,
		type_parameter,
		Description,
		technologies_paractises,
		parameters_conditions,
		region,
		control_paractises,
		properties,
		emissionsfactor_value,
		emissionsfactor_units,
		ipcc_equation,
		data_source,
		ipcc_worksheet,
		technical_reference,
		dataset_name
FROM waste_ef_split
WHERE ipcc_sector != '')
SELECT ef_id,
		ipcc_sector,
		gas,
		type_parameter,
		description,
		technologies_paractises,
		parameters_conditions,
		region,
		control_paractises,
		properties,
		emissionsfactor_value,
		emissionsfactor_units,
		ipcc_equation,
		data_source,
		ipcc_worksheet,
		technical_reference,
		dataset_name,
		trim(COALESCE(technologies_paractises, '') || ' ' || COALESCE(parameters_conditions,'') || '' || COALESCE(control_paractises,'') || ' '|| COALESCE(properties,'')) as emissionfactor_details
FROM waste_ef_split_gas
WHERE gas != ''