apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  labels:
    app: api-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
        - name: api-demo
          image: ghcr.io/open-earth-foundation/cc-api-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: CC_ORIGIN
              value: "https://citycatalyst.io"
            - name: CLIENT_ID
              value: "changeme"
