import { beforeAll, describe, expect, it } from "@jest/globals";
import { readFileSync } from "node:fs";
import { buildReportPdf } from "@/app/[lng]/cities/[cityId]/MEED/[inventory]/results/report/meedReportPdf";

// Serve the real logo from disk so the branded path is exercised, not skipped.
beforeAll(() => {
  const png = readFileSync("public/assets/citycatalyst-logo-blue.png");
  (global as any).fetch = async () => ({
    ok: true,
    blob: async () => ({ __png: png }),
  });
  (global as any).FileReader = class {
    onloadend: (() => void) | null = null;
    onerror: (() => void) | null = null;
    result = "";
    readAsDataURL(blob: any) {
      this.result = `data:image/png;base64,${Buffer.from(blob.__png).toString("base64")}`;
      this.onloadend?.();
    }
  };
});

const snapshot = `**The ask:** Support municipal delivery to install renewable energy on water treatment, pumping, and distribution systems, subject to the conditions identified in the legal review.

In Antofagasta, the action "Integrate renewables into municipal water systems" ranks 1 of 20.

| What we checked | Reading | Detail |
|---|---|---|
| Climate benefit | Very high | The prioritization rates the action's direct emissions-reduction potential as very high. |
| City fit | Strong | The local feasibility assessment rates this action as strong. |
| Policy backing | Medium | 33 findings across 8 documents. |
| Legal room to act | Conditional | Authority exists but is conditional, ambiguous, or mediated by an enabling instrument. |
| Funding | Feasible with own budget | Within the city's own budget and capacity. |
| Track record | Not available | Not available. |

The action combines strong climate benefit and city fit with conditional legal room to act and no available track-record evidence.`;

const policy = `Policy backing for Integrate renewables into municipal water systems is medium (0.65), based on 33 findings across 8 documents. The five excerpts below prioritize direct commitments before broader governance provisions.

| Document | Page | Signal | What the document says |
|---|---:|---|---|
| Plan de Acción Regional de Cambio Climático Antofagasta | p. 88 | Commits (action) | Translated excerpt: Implement water recovery systems. |
| Plan de Acción Regional de Cambio Climático Antofagasta | p. 68 | Commits (action) | Translated excerpt: Promote water efficiency in human settlements. |
| Plan de Acción Regional de Cambio Climático Antofagasta | p. 129 | Commits (action) | Translated excerpt: Promote and disseminate the programme offerings related to non-conventional renewable energy from public services. |
| Plan de Mitigación Sector Infraestructura | p. 22 | Governs (governance) | Translated excerpt: The main function associated with this sector is assumed by the Ministerio de Obras Públicas (MOP). |`;

const finance = `The finance assessment considers this action feasible within the city's own budget and capacity. The opportunities below are options to assess, not confirmed funding routes.

### Financing opportunities to assess

| Opportunity | Funder | Support | Status | Link |
|---|---|---|---|---|
| Asistencia Técnica para Municipios en Gestión Energética Local | Ministerio de Energía / AgenciaSE | Technical assistance; in-kind support with no cash grant | Ongoing (recorded 8 June 2026) | [Programme page](https://energia.gob.cl/a) |
| Comuna Energética | Ministerio de Energía / AgenciaSE | Technical assistance; co-financing through competitive application windows | Ongoing (recorded 8 June 2026) | [Programme page](https://energia.gob.cl/b) |
| Casa Solar | Ministerio de Energía / AgenciaSE | Blended support: co-financing of up to approximately 50% of rooftop photovoltaic systems | Open (recorded 8 June 2026) | [Programme page](https://energia.gob.cl/c) |

Next steps:

1. Confirm current terms and eligibility with the funder.
2. Assess which rural APR systems qualify.
3. Prepare a municipal counterpart commitment.`;

const meta = {
  title: "Climate action report",
  cityName: "Antofagasta",
  subtitle: "One prioritized action",
  limitationsLabel: "Limitations",
  generatedBy: "Generated by CityCatalyst",
  generatedOn: "Generated on 09/09/2026",
  pageLabel: "Page",
  ofLabel: "of",
};

const document = {
  actionId: "icare_0024",
  actionName: "Integrate renewables into municipal water systems",
  sections: [
    {
      key: "snapshot",
      title: "Snapshot",
      markdown: snapshot,
      limitations: [
        "City-level quantified emissions reductions are not available for this action.",
        "Named comparable projects and track-record data are not available.",
      ],
    },
    {
      key: "policy",
      title: "Policy Backing",
      markdown: policy,
      limitations: [],
    },
    {
      key: "finance",
      title: "Financing, Precedents & Pathway",
      markdown: finance,
      limitations: [
        "Current terms and eligibility for this action still need to be confirmed.",
      ],
    },
  ],
};

const render = async (documents = [document]) => {
  const pdf = await buildReportPdf(documents, meta);
  return {
    pdf,
    bytes: Buffer.from(pdf.output("arraybuffer")),
  };
};

// End-to-end over the real chapter shapes the prompts emit. The layout itself
// cannot be asserted, but the things that were actually broken can be.
describe("report pdf", () => {
  it("renders multi-page content without throwing", async () => {
    const { pdf } = await render();
    expect(pdf.getNumberOfPages()).toBeGreaterThan(1);
  });

  it("turns table cell links into real PDF annotations", async () => {
    const { bytes } = await render();
    const uris = bytes.toString("latin1").match(/\/URI/g) ?? [];
    // "Programme page" wraps, so each link contributes more than one rect.
    expect(uris.length).toBeGreaterThanOrEqual(3);
    expect(bytes.toString("latin1")).toContain("https://energia.gob.cl/a");
  });

  it("stays small enough to email, despite embedding the logo", async () => {
    const { bytes } = await render();
    // Uncompressed, the raw logo bitmap alone is ~850 KB.
    expect(bytes.length).toBeLessThan(200_000);
  });

  it("gives each action its own page", async () => {
    const one = await render();
    const two = await render([
      document,
      { ...document, actionId: "icare_0027" },
    ]);
    expect(two.pdf.getNumberOfPages()).toBeGreaterThan(
      one.pdf.getNumberOfPages(),
    );
  });

  it("survives a document with no sections", async () => {
    const { pdf } = await render([
      { actionId: "x", actionName: "Empty action", sections: [] },
    ]);
    expect(pdf.getNumberOfPages()).toBe(1);
  });
});
