name: Push HIAP to GHCR and deploy to EKS Test
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "hiap/**"
      - ".github/workflows/hiap-test.yml"

concurrency:
  group: hiap-test
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_HIAP_TEST }}
      LANGCHAIN_PROJECT: hiap-test
      LANGCHAIN_PROJECT_NAME_PRIORITIZER: hiap-test-prioritizer
      LANGCHAIN_PROJECT_NAME_PLAN_TRANSLATION: hiap-test-plan-translation
      LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
      LANGCHAIN_TRACING_V2: false
      OPENAI_MODEL_NAME_PLAN_CREATOR: gpt-4.1
      OPENAI_MODEL_NAME_EXPLANATIONS: gpt-4.1-mini
      OPENAI_MODEL_NAME_PLAN_CREATOR_LEGACY: gpt-4.1
      OPENAI_MODEL_NAME_PLAN_TRANSLATION: gpt-4.1-mini
      EXPLANATIONS_ENABLED: false
      BULK_CONCURRENCY: 1
      XGBOOST_NUM_THREADS: 1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-v2-${{ hashFiles('hiap/**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-v2-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hiap/requirements.txt

      - name: Run all tests
        working-directory: hiap
        run: |
          pytest -c pytest.ini -m "not slow"

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      REGISTRY: ghcr.io
      REPOSITORY: open-earth-foundation/citycatalyst-hiap

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Git commit hash
        id: vars
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: hiap
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ steps.vars.outputs.commit_hash }}
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_EKS_DEV_USER }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_EKS_DEV_USER }}
      EKS_DEV_NAME: ${{ secrets.EKS_DEV_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Creating kubeconfig file
        run: aws eks update-kubeconfig --name ${{secrets.EKS_DEV_NAME}} --region us-east-1

      - name: Testing connection to EKS
        run: kubectl get pods -n default

      - name: Deploying test service
        run: |
          kubectl apply -f hiap/k8s/deployment-test.yml
          kubectl apply -f hiap/k8s/service-test.yml

          kubectl set env deployment/hiap-test \
            OPENAI_MODEL_NAME_EXPLANATIONS=gpt-4.1-mini \
            OPENAI_MODEL_NAME_PLAN_CREATOR_LEGACY=gpt-4.1 \
            OPENAI_MODEL_NAME_PLAN_CREATOR=gpt-4.1 \
            OPENAI_MODEL_NAME_PLAN_TRANSLATION=gpt-4.1-mini \
            LANGCHAIN_PROJECT=hiap-test \
            LANGCHAIN_PROJECT_NAME_PRIORITIZER=hiap-test-prioritizer \
            LANGCHAIN_PROJECT_NAME_PLAN_TRANSLATION=hiap-test-plan-translation \
            LANGCHAIN_ENDPOINT=https://api.smith.langchain.com \
            LANGCHAIN_TRACING_V2=true \
            S3_BUCKET_NAME=openearth.cap \
            EXPLANATIONS_ENABLED=true \
            BULK_CONCURRENCY=10 \
            XGBOOST_NUM_THREADS=1 \
            LOG_PARALLELISM=1 \
            LOG_LEVEL=INFO \
            OPENAI_API_KEY=${{secrets.OPENAI_API_KEY_HIAP_TEST}} \
            LANGCHAIN_API_KEY=${{secrets.LANGCHAIN_API_KEY}} \
            AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID_HIAP}} \
            AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY_HIAP}}

          kubectl rollout restart deployment hiap-test -n default
          kubectl rollout status deployment/hiap-test -n default
