name: Push Web app to GHCR and deploy to EKS

on:
  workflow_dispatch:
  push:
    paths:
      - app/**
      - k8s/test/cc-test-migrate.yml
      - k8s/test/cc-test-web-deploy.yml
      - k8s/test/cc-test/web.yml
      - .github/workflows/web-test.yml
    branches: [ "main" ]

jobs:
  runTests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      NEXTAUTH_SECRET: "diTMz/XLX4edSmmfzwJtmzKjCJGRt81Gf0PdjO3IPs8="
      NEXTAUTH_URL: "http://localhost:3000"
      CDP_API_KEY: ${{ secrets.CDP_API_KEY_TEST }}
      CDP_MODE: "test"
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Set up database
        env:
          GLOBAL_API_URL: https://ccglobal-test.openearth.dev
        run: |
          docker run --name github_action_postgresql -d -p 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_PASSWORD="" postgres
          sleep 10
          createuser -w -h localhost -p 5432 -U postgres citycatalyst
          createdb -w -h localhost -p 5432 -U postgres citycatalyst -O citycatalyst
          cp env.example .env
          npm run db:migrate
          npm run db:seed
          npm run sync-catalogue
          npm run sync-emissions-factors
          npm run sync-formula-values

      - name: Setup Environment Variables
        run: |
          echo "NEXT_PUBLIC_API_URL=https://citycatalyst-test.openearth.dev" >> .env.local
          echo "NEXT_PUBLIC_OPENCLIMATE_API_URL=https://openclimate.openearth.dev" >> .env.local

      - name: Run NextJS build
        run: npm run build

      - name: Run tests and generate coverage file
        run: npm run api:test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload coverage reports to Codecov
        continue-on-error: true
        uses: codecov/codecov-action@v4.0.1
        with:
          fail_ci_if_error: false
          flags: unittests
          name: citycatalyst-backend
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Open-Earth-Foundation/CityCatalyst

      - name: Shut down database
        run: docker stop github_action_postgresql

  pushToGHCR:
    needs: runTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push full image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: ./app
          target: full-build
          push: true
          tags: |
            ghcr.io/open-earth-foundation/citycatalyst:${{ github.sha }}
            ghcr.io/open-earth-foundation/citycatalyst:main
          build-args: |
            NEXT_PUBLIC_API_URL=https://citycatalyst-test.openearth.dev
            NEXT_PUBLIC_OPENCLIMATE_API_URL=https://openclimate.openearth.dev
          cache-from: |
            type=gha,scope=citycatalyst-shared
            type=gha,scope=${{ github.ref_name }}
            type=gha,scope=main
            type=gha,scope=develop
          cache-to: type=gha,mode=max,scope=citycatalyst-shared

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: ./app
          target: release
          push: true
          tags: |
            ghcr.io/open-earth-foundation/citycatalyst-web:${{ github.sha }}
            ghcr.io/open-earth-foundation/citycatalyst-web:main
          build-args: |
            NEXT_PUBLIC_API_URL=https://citycatalyst-test.openearth.dev
            NEXT_PUBLIC_OPENCLIMATE_API_URL=https://openclimate.openearth.dev
          cache-from: |
            type=gha,scope=citycatalyst-shared
            type=gha,scope=${{ github.ref_name }}
            type=gha,scope=main
            type=gha,scope=develop
          cache-to: type=gha,mode=max,scope=citycatalyst-shared

  deployToEKS:
    needs: pushToGHCR
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_EKS_DEV_USER }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_EKS_DEV_USER }}
      EKS_DEV_NAME: ${{ secrets.EKS_DEV_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Creating kubeconfig file
        run: aws eks update-kubeconfig --name ${{secrets.EKS_DEV_NAME}} --region us-east-1

      - name: Testing connection to EKS
        run: kubectl get pods -n default

      - name: Deploying service
        run: |
          kubectl create -f k8s/test/cc-test-migrate.yml -n default
          kubectl create -f k8s/test/cc-test-seed.yml -n default
          kubectl apply -f k8s/test/cc-test-sync-catalogue.yml -n default
          kubectl apply -f k8s/test/cc-test-web-deploy.yml -n default
          kubectl set env deployment/cc-test-web-deploy \
            SMTP_USER=${{secrets.SMTP_USER}} \
            SMTP_PASSWORD=${{secrets.SMTP_PASSWORD}} \
            NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}} \
            RESET_TOKEN_SECRET=${{secrets.RESET_TOKEN_SECRET}} \
            VERIFICATION_TOKEN_SECRET=${{secrets.VERIFICATION_TOKEN_SECRET}} \
            OPENAI_API_KEY=${{secrets.OPENAI_API_KEY_TEST}} \
            "OPENAI_ASSISTANT_ID=asst_4if8qn6W8Vlxwbf2cuyH8OFU" \
            HUGGINGFACE_API_KEY=${{secrets.HUGGINGFACE_API_KEY}} \
            "ADMIN_EMAILS=${{secrets.ADMIN_EMAILS}}" \
            "ADMIN_NAMES=${{secrets.ADMIN_NAMES}}" \
            "DEFAULT_ADMIN_EMAIL=${{secrets.DEFAULT_ADMIN_EMAIL}}" \
            "DEFAULT_ADMIN_PASSWORD=${{secrets.DEFAULT_ADMIN_PASSWORD}}" \
            "HOST=https://citycatalyst-test.openearth.dev" \
            "NEXTAUTH_URL=https://citycatalyst-test.openearth.dev" \
            "NEXT_PUBLIC_API_URL=https://citycatalyst-test.openearth.dev" \
            "GLOBAL_API_URL=https://ccglobal-test.openearth.dev" \
            "HIAP_API_URL=http://hiap-service-dev" \
            "NEXT_PUBLIC_OPENCLIMATE_API_URL=https://openclimate.openearth.dev" \
            "OPENCLIMATE_API_URL=https://openclimate.openearth.dev" \
            "NEXT_PUBLIC_FEATURE_FLAGS=ENTERPRISE_MODE,CAP_TAB_ENABLED,ACCOUNT_SETTINGS_ENABLED,ANALYTICS_ENABLED" \
            "NEXT_PUBLIC_POSTHOG_KEY=${{secrets.NEXT_PUBLIC_POSTHOG_KEY}}" \
            "NEXT_PUBLIC_POSTHOG_HOST=https://eu.i.posthog.com" \
            "NEXT_PUBLIC_DEPLOYMENT_ENV=staging" \
            "AWS_FILE_UPLOAD_S3_BUCKET_ID=citycatalyst-files" \
            "AWS_FILE_UPLOAD_REGION=us-east-1" \
            "AWS_REGION"=${{secrets.AWS_REGION}} \
            "AWS_ACCESS_KEY_ID"=${{secrets.AWS_ACCESS_KEY_ID}} \
            "AWS_SECRET_ACCESS_KEY"=${{secrets.AWS_SECRET_ACCESS_KEY}} \
            "AWS_S3_BUCKET_ID"=${{secrets.AWS_S3_BUCKET_ID}} \
            CDP_API_KEY=${{secrets.CDP_API_KEY_TEST}}
          kubectl create -f k8s/test/cc-test-create-admin.yml -n default
          kubectl rollout restart deployment cc-test-web-deploy -n default
